### ISSUE TITLE
Lua 5.3 bindings are to Lua 5.2

### ISSUE THREAD

**Issue by Ayplow** [BindBC/bindbc-lua#1]
https://github.com/BindBC/bindbc-lua/blob/8ff70f214f964df8b0702d446bc4002813d18421/source/bindbc/lua/v53/binddynamic.d#L345-L364

Looks like the 5.3 bindings just arent done yet, but it was a pain to figure out why it wasnt finding my shared library, so this issue can just serve as a warning

**Comment by mdparker** [comment]
No, the bindings are complete. I simply forgot to change the library names when I copied the loader code from the 5.2 loader. Fixed in 0.1.1.

**Comment by Ayplow** [comment]
You missed a spot~
https://github.com/BindBC/bindbc-lua/blob/4703e75dbf8d9c5965dc84eb08d1837ba3284ee4/source/bindbc/lua/v53/binddynamic.d#L526

**Comment by mdparker** [comment]
Thanks. Fixed in 0.1.2.
